name: iOS starter workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: macOS-latest
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=14.5,name=iPhone 11']
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Check Simulators
        run: instruments -s devices
      - name: Xcode Version
        run: xcodebuild -version
      - name: Availables SDKs
        run: xcodebuild -showsdks
      - name: Build and test
        run: |
          xcodebuild clean test \
            -project funfun.xcodeproj \
            -scheme funfun \
            -destination "${destination}" \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
          bash <(curl -s https://codecov.io/bash)
        env: 
         destination: ${{ matrix.destination }}
